name: ""
description: ""

url: "http://localhost:4000/"  
#url: "http://tangoe.github.io/Mobile-Procurement-API-Documentation/" 

#kramdown:
#  input: GFM

#markdown: kramdown
#kramdown:
#  use_coderay: true

#markdown: redcarpet
#markdown: rdiscount

# Conversion
#markdown: redcarpet
#highlighter: rouge 
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
