name: ""
description: ""

url: "http://localhost:4000" 
# url: "http://tangoe.github.io/Mobile-Procurement-API-Documentation/" 
# url: "/Mobile-Procurement-API-Documentation" 
# url: ""

# paginate: 10
# markdown: rdiscount
# permalink: pretty
# pygments: true


#kramdown:
#  input: GFM



